---
abstract: 'File-finding iterator'
author:
  - 'Andy Lester <andy@petdance.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Next
no_index:
  directory:
    - t
    - inc
requires:
  File::Copy: '0'
  File::Spec: '0'
  File::Temp: '0.22'
  Test::More: '0.88'
resources:
  bugtracker: http://github.com/petdance/file-next/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/petdance/file-next/tree/master
version: '1.18'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
